### ISSUE TITLE
Support for X.509 certificates in SFR FPT_TUD_EXT

### ISSUE THREAD

**Issue by ansukert** [HCD-iTC/HCD-iTC-Template#270]
**What is the change request for the cPP? Please describe.**
Comment against HCD cPP Version 0.10 dated 8/30/2021 from Ryuichiro Ohya-san of Fufi Film Business Innovation:

1. A.4.1.2. FIA_X509_EXT.2 X.509 Certificate Authentication, Application Note 113, last paragraph, pg. 88: The ST author must include FIA_X509_EXT.1/Rev in all instances except when only SSH is selected within FTP_ITC.1 or FPT_ITT.1, and implementation is limited to public-key authentication that does not rely on X.509 certificates. _Additionally, FIA_X509_EXT.1/Rev must also be included if FPT_TUD_EXT is included in the ST._
	-------------
It looks that the TSF must support X509.certificate validation in FPT_TUD_EXT. 
However, FPT_TUD_EXT.1.3 does not limit digital signature mechanism only to X509 certificate. 

Should change the last sentence in this paragraph to read: Additionally, FIA_X509_EXT.2 must also be included if “X.509 certificate” is selected in FPT_TUD_EXT.1.3.

Note: The same comment applies to Section A.4.1.1. FIA_X509_EXT.1 X.509 Certificate Validation, Application Note 112, Last Paragraph, pg. 87: The last sentence of that paragraph should be changed to: Additionally, FIA_X509_EXT.1/Rev must also be included if “X.509 certificate” is selected in FPT_TUD_EXT.1.3. 

**Describe the solution you'd like**
Implement the suggested corrective action above

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by ansukert** [comment]
Update to correct bolding

**Comment by Ryuichiro-Ohya-FX** [comment]
I suggested to delete the sentence because it is incorrect. But, modifying the sentence may be better.
Please find the attached proposal for modificatio
[collaborative Protection Profile for Hardcopy Devices.docx](https://github.com/HCD-iTC/HCD-iTC-Template/files/7351008/collaborative.Protection.Profile.for.Hardcopy.Devices.docx)
n.

**Comment by ansukert** [comment]
Update to reflect change in this issue by Ohya-san reported at the 10/28/21 HCD iTC Meeting.
